### PR TITLE
add new file

### PR DESCRIPTION
**Pull request by paulirish**

### CODE REVIEW

**Comment by chdsbd** [comment]
Hi @paulirish, I saw via logs that there is a config parsing issue with kodiak for this repo. Basically this kodiak config isn't valid: https://github.com/paulirish/lighthouse/commit/f813d08df93854c01c3eece3790fc73cf47e18f3

There are some valid config options here: https://github.com/chdsbd/kodiak/tree/master/kodiak/test/fixtures/config

This is the Python code that parses the config: https://github.com/chdsbd/kodiak/blob/master/kodiak/config.py

I've opened an issue to track this usability issue here: https://github.com/chdsbd/kodiak/issues/102

**Comment by paulirish** [comment]
@chdsbd ha! such service. :) Thank you.

My style is to always delete the commit message body... so that's what I thought I was doing. It looks like the current options don't give me this option. All good.

**Comment by chdsbd** [comment]
I think marking `kodiakhq: status` as a required check will prevent kodiak from merging the PR as kodiak always sets a "neutral" check run result, not the "success" that a required check needs.

I've added an issue to address this: https://github.com/chdsbd/kodiak/issues/107

**Comment by paulirish** [comment]
@chdsbd 	coolness. Thanks :D

**Pull request merged**
